# Generated by Django 6.0.2 on 2026-02-12 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MeasureGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Measure group name"),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Measure group description"),
                ),
                (
                    "icon",
                    models.ImageField(
                        upload_to="measure_groups", verbose_name="Measure group icon"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Measure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Measure name")),
                (
                    "short_description",
                    models.CharField(
                        max_length=255, verbose_name="Measure short description"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogue.measuregroup",
                        verbose_name="Measure group",
                    ),
                ),
            ],
        ),
    ]
