# Generated by Django 6.0.2 on 2026-02-12 10:26

import catalogue.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="measure",
            name="aesthetics",
            field=catalogue.fields.ScoreField(default=1, verbose_name="Aesthetics"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="measure",
            name="air",
            field=catalogue.fields.ScoreField(default=1, verbose_name="Air"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="measure",
            name="biodiversity",
            field=catalogue.fields.ScoreField(default=1, verbose_name="Biodiversity"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="measure",
            name="temperature",
            field=catalogue.fields.ScoreField(default=1, verbose_name="Temperature"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="measure",
            name="water",
            field=catalogue.fields.ScoreField(default=1, verbose_name="Water"),
            preserve_default=False,
        ),
    ]
