# Generated by Django 6.0.6 on 2026-06-30 11:20

import django.db.models.deletion
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalogue",
            "0002_measure_aesthetics_measure_air_measure_biodiversity_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Advantage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("advantage", models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name="AdvatageCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("advantage_category", models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name="Law",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Limitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("limitation", models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name="LocationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_type", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="MainAdvantage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("advantage", models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name="PreDesign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prereqisite", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="SDG",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sdg_number", models.PositiveSmallIntegerField()),
                ("sdg_name", models.CharField(max_length=100)),
                ("icon", models.ImageField(upload_to="")),
            ],
        ),
        migrations.AlterModelOptions(
            name="measure",
            options={"verbose_name": "Measure", "verbose_name_plural": "Measures"},
        ),
        migrations.AlterModelOptions(
            name="measuregroup",
            options={
                "verbose_name": "Measure group",
                "verbose_name_plural": "Measure groups",
            },
        ),
        migrations.AddField(
            model_name="measure",
            name="budget_choices",
            field=models.CharField(
                choices=[("L", "Low"), ("M", "Medium"), ("H", "High")],
                default=1,
                max_length=1,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="measure",
            name="combine",
            field=models.ManyToManyField(to="catalogue.measure"),
        ),
        migrations.AddField(
            model_name="measure",
            name="complexity_of_realization",
            field=models.CharField(
                choices=[("L", "Low"), ("M", "Medium"), ("H", "High")],
                default=1,
                max_length=1,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="measure",
            name="description",
            field=markdownx.models.MarkdownxField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="measure",
            name="diy",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="measure",
            name="measure_size",
            field=models.CharField(
                choices=[("P", "Point"), ("L", "Line"), ("A", "Area")],
                default=1,
                max_length=1,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="measure",
            name="price",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="measure",
            name="purpose",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="measure",
            name="time_horizon",
            field=models.CharField(
                choices=[("L", "Low"), ("M", "Medium"), ("H", "High")],
                default=1,
                max_length=1,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="measure",
            name="units",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="measure",
            name="advantage",
            field=models.ManyToManyField(to="catalogue.advantage"),
        ),
        migrations.AddField(
            model_name="advantage",
            name="advantage_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogue.advatagecategory",
            ),
        ),
        migrations.AddField(
            model_name="measure",
            name="law",
            field=models.ManyToManyField(to="catalogue.law"),
        ),
        migrations.AddField(
            model_name="measure",
            name="limitation",
            field=models.ManyToManyField(to="catalogue.limitation"),
        ),
        migrations.AddField(
            model_name="measure",
            name="location_type",
            field=models.ManyToManyField(to="catalogue.locationtype"),
        ),
        migrations.AddField(
            model_name="measure",
            name="main_advantage",
            field=models.ManyToManyField(to="catalogue.mainadvantage"),
        ),
        migrations.CreateModel(
            name="Performance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("performance", models.CharField(max_length=100)),
                (
                    "measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogue.measure",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="measure",
            name="sdg",
            field=models.ManyToManyField(to="catalogue.sdg"),
        ),
    ]
