# Generated by Django 6.0.6 on 2026-06-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0003_advantage_advatagecategory_law_limitation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="measuregroup",
            name="name",
        ),
        migrations.AddField(
            model_name="measuregroup",
            name="name_cs",
            field=models.CharField(
                default=1, max_length=100, verbose_name="Measure group name (Czech)"
            ),
            preserve_default=False,
        ),
    ]
