# Generated by Django 6.0.6 on 2026-06-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0004_remove_measuregroup_name_measuregroup_name_cs"),
    ]

    operations = [
        migrations.RenameField(
            model_name="measuregroup",
            old_name="description",
            new_name="description_cs",
        ),
        migrations.AddField(
            model_name="measuregroup",
            name="description_en",
            field=models.TextField(default=1, verbose_name="Measure group description"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="measuregroup",
            name="name_en",
            field=models.CharField(
                default=1, max_length=100, verbose_name="Measure group name (en)"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="measuregroup",
            name="name_cs",
            field=models.CharField(
                max_length=100, verbose_name="Measure group name (cs)"
            ),
        ),
    ]
