# Generated by Django 6.0.6 on 2026-06-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0005_rename_description_measuregroup_description_cs_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measuregroup",
            name="description_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Measure group description"
            ),
        ),
        migrations.AlterField(
            model_name="measuregroup",
            name="name_en",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Measure group name (en)",
            ),
        ),
    ]
