# Generated by Django 6.0.6 on 2026-06-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0006_alter_measuregroup_description_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measuregroup",
            name="description_cs",
            field=models.TextField(verbose_name="Measure group description (cs)"),
        ),
        migrations.AlterField(
            model_name="measuregroup",
            name="description_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Measure group description (en)"
            ),
        ),
    ]
