# Generated by Django 6.0.6 on 2026-06-30 11:58

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0007_alter_measuregroup_description_cs_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="measure",
            old_name="description",
            new_name="description_cs",
        ),
        migrations.RemoveField(
            model_name="measure",
            name="name",
        ),
        migrations.RemoveField(
            model_name="measure",
            name="short_description",
        ),
        migrations.AddField(
            model_name="measure",
            name="description_en",
            field=markdownx.models.MarkdownxField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="measure",
            name="name_cs",
            field=models.CharField(
                default=1, max_length=100, verbose_name="Measure name (cs)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="measure",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Measure name (en)"
            ),
        ),
        migrations.AddField(
            model_name="measure",
            name="short_description_cs",
            field=models.CharField(
                default=1, max_length=255, verbose_name="Measure short description (cs)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="measure",
            name="short_description_en",
            field=models.CharField(
                default=1, max_length=255, verbose_name="Measure short description (en)"
            ),
            preserve_default=False,
        ),
    ]
