# Generated by Django 6.0.6 on 2026-06-30 12:57

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0008_rename_description_measure_description_cs_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="locationtype",
            options={
                "verbose_name": "Location type",
                "verbose_name_plural": "Location types",
            },
        ),
        migrations.RemoveField(
            model_name="locationtype",
            name="location_type",
        ),
        migrations.AddField(
            model_name="locationtype",
            name="location_type_cs",
            field=models.CharField(
                default=1, max_length=20, verbose_name="Location type (cs)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="locationtype",
            name="location_type_en",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Location type (en)"
            ),
        ),
        migrations.AlterField(
            model_name="measure",
            name="description_cs",
            field=markdownx.models.MarkdownxField(
                verbose_name="Measure description (cs)"
            ),
        ),
        migrations.AlterField(
            model_name="measure",
            name="description_en",
            field=markdownx.models.MarkdownxField(
                verbose_name="Measure description (en)"
            ),
        ),
    ]
