# Generated by Django 6.0.6 on 2026-06-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0009_alter_locationtype_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mainadvantage",
            old_name="advantage",
            new_name="advantage_cs",
        ),
        migrations.AlterField(
            model_name="measure",
            name="location_type",
            field=models.ManyToManyField(
                to="catalogue.locationtype", verbose_name="Location type"
            ),
        ),
    ]
