# Generated by Django 6.0.6 on 2026-06-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0010_rename_advantage_mainadvantage_advantage_cs_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mainadvantage",
            options={
                "verbose_name": "Main advantage",
                "verbose_name_plural": "Main advantages",
            },
        ),
        migrations.AddField(
            model_name="mainadvantage",
            name="advantage_en",
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
