# Generated by Django 6.0.6 on 2026-06-30 13:21

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0011_alter_mainadvantage_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measure",
            name="description_en",
            field=markdownx.models.MarkdownxField(
                blank=True, null=True, verbose_name="Measure description (en)"
            ),
        ),
        migrations.AlterField(
            model_name="measure",
            name="main_advantage",
            field=models.ManyToManyField(
                to="catalogue.mainadvantage", verbose_name="Main advantage"
            ),
        ),
        migrations.AlterField(
            model_name="measure",
            name="short_description_en",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Measure short description (en)",
            ),
        ),
    ]
