# Generated by Django 6.0.6 on 2026-06-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0012_alter_measure_description_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measure",
            name="diy",
            field=models.BooleanField(default=False),
        ),
    ]
