# Generated by Django 6.0.6 on 2026-06-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0013_alter_measure_diy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measure",
            name="price",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
