# Generated by Django 6.0.6 on 2026-07-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0014_alter_measure_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="advatagecategory",
            options={
                "verbose_name": "Advantage category",
                "verbose_name_plural": "Advantage categories",
            },
        ),
        migrations.RemoveField(
            model_name="advatagecategory",
            name="advantage_category",
        ),
        migrations.AddField(
            model_name="advatagecategory",
            name="advantage_category_cs",
            field=models.CharField(
                default=1, max_length=35, verbose_name="Advantage category (cs)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="advatagecategory",
            name="advantage_category_en",
            field=models.CharField(
                blank=True,
                max_length=35,
                null=True,
                verbose_name="Advantage category (en)",
            ),
        ),
    ]
