# Generated by Django 6.0.6 on 2026-07-02 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0015_alter_advatagecategory_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="measure",
            name="advantage",
        ),
        migrations.DeleteModel(
            name="Advantage",
        ),
    ]
