# Generated by Django 6.0.6 on 2026-07-02 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0016_remove_measure_advantage_delete_advantage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="measure",
            name="main_advantage",
        ),
    ]
