# Generated by Django 6.0.6 on 2026-07-02 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0017_remove_measure_main_advantage"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MainAdvantage",
            new_name="Advantage",
        ),
        migrations.AlterModelOptions(
            name="advantage",
            options={"verbose_name": "Advantage", "verbose_name_plural": "Advantages"},
        ),
    ]
