# Generated by Django 6.0.6 on 2026-07-02 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0018_rename_mainadvantage_advantage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="advantage",
            name="advantage_category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogue.advatagecategory",
                verbose_name="Advantage category",
            ),
            preserve_default=False,
        ),
    ]
