# Generated by Django 6.0.6 on 2026-07-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0019_advantage_advantage_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="measure",
            name="advantage",
            field=models.ManyToManyField(
                related_name="advantage",
                to="catalogue.advantage",
                verbose_name="Advantage",
            ),
        ),
        migrations.AddField(
            model_name="measure",
            name="main_advantage",
            field=models.ManyToManyField(
                related_name="main_advantage",
                to="catalogue.advantage",
                verbose_name="Main advantage",
            ),
        ),
    ]
