# Generated by Django 6.0.6 on 2026-07-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0020_measure_advantage_measure_main_advantage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="limitation",
            options={
                "verbose_name": "Limitation",
                "verbose_name_plural": "Limitations",
            },
        ),
        migrations.RenameField(
            model_name="limitation",
            old_name="limitation",
            new_name="limitation_cs",
        ),
        migrations.AddField(
            model_name="limitation",
            name="limitation_en",
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name="measure",
            name="limitation",
            field=models.ManyToManyField(
                to="catalogue.limitation", verbose_name="Limitation"
            ),
        ),
    ]
