# Generated by Django 6.0.6 on 2026-07-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0021_alter_limitation_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="limitation",
            name="limitation_cs",
            field=models.CharField(max_length=35, verbose_name="Limitation (cs)"),
        ),
        migrations.AlterField(
            model_name="limitation",
            name="limitation_en",
            field=models.CharField(
                blank=True, max_length=35, null=True, verbose_name="Limitation (en)"
            ),
        ),
    ]
