# Generated by Django 6.0.6 on 2026-07-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0022_alter_limitation_limitation_cs_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measure",
            name="budget_choices",
            field=models.CharField(
                choices=[("L", "Low"), ("M", "Medium"), ("H", "High")],
                max_length=1,
                verbose_name="Budget",
            ),
        ),
        migrations.AlterField(
            model_name="measure",
            name="complexity_of_realization",
            field=models.CharField(
                choices=[("L", "Low"), ("M", "Medium"), ("H", "High")],
                max_length=1,
                verbose_name="Complexity of realization",
            ),
        ),
        migrations.AlterField(
            model_name="measure",
            name="diy",
            field=models.BooleanField(default=False, verbose_name="DIY"),
        ),
        migrations.AlterField(
            model_name="measure",
            name="measure_size",
            field=models.CharField(
                choices=[("P", "Point"), ("L", "Line"), ("A", "Area")],
                max_length=1,
                verbose_name="Measure size",
            ),
        ),
        migrations.AlterField(
            model_name="measure",
            name="price",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Price"
            ),
        ),
        migrations.AlterField(
            model_name="measure",
            name="time_horizon",
            field=models.CharField(
                choices=[("L", "Low"), ("M", "Medium"), ("H", "High")],
                max_length=1,
                verbose_name="Time horizon",
            ),
        ),
        migrations.AlterField(
            model_name="measure",
            name="units",
            field=models.CharField(max_length=10, verbose_name="Units"),
        ),
    ]
