# Generated by Django 6.0.6 on 2026-07-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0023_alter_measure_budget_choices_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="law",
            options={
                "verbose_name": "Legislation",
                "verbose_name_plural": "Legislations",
            },
        ),
        migrations.AlterModelOptions(
            name="sdg",
            options={
                "verbose_name": "Sustainable Development Goal",
                "verbose_name_plural": "Sustainable Development Goals",
            },
        ),
        migrations.AlterField(
            model_name="sdg",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to="sdg_icons"),
        ),
    ]
