# Generated by Django 6.0.6 on 2026-07-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0024_alter_law_options_alter_sdg_options_alter_sdg_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="law",
            name="url",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
