# Generated by Django 6.0.6 on 2026-07-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0025_law_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measure",
            name="combine",
            field=models.ManyToManyField(
                blank=True,
                related_name="related_measures",
                to="catalogue.measure",
                verbose_name="Related measures",
            ),
        ),
    ]
