# Generated by Django 6.0.7 on 2026-07-17 10:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0026_alter_measure_combine"),
    ]

    operations = [
        migrations.CreateModel(
            name="TempMesureGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "old_pk",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="Old primary key"
                    ),
                ),
                (
                    "name_cs",
                    models.CharField(
                        max_length=100, verbose_name="Measure group name (cs)"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Measure group name (en)",
                    ),
                ),
                (
                    "description_cs",
                    models.TextField(verbose_name="Measure group description (cs)"),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Measure group description (en)",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        upload_to="temp_measure_groups",
                        verbose_name="Measure group icon",
                    ),
                ),
            ],
        ),
    ]
