# Generated by Django 6.0.7 on 2026-07-17 11:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0028_copy_measure_groups_to_temp"),
    ]

    operations = [
        migrations.CreateModel(
            name="TempLocationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "old_pk",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="Old primary key"
                    ),
                ),
                (
                    "location_type_cs",
                    models.CharField(max_length=20, verbose_name="Location type (cs)"),
                ),
                (
                    "location_type_en",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Location type (en)",
                    ),
                ),
            ],
        ),
    ]
