# Generated by Django 6.0.7 on 2026-07-17 11:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0030_copy_location_types_to_temp"),
    ]

    operations = [
        migrations.CreateModel(
            name="TempLimitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "old_pk",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="Old primary key"
                    ),
                ),
                (
                    "limitation_cs",
                    models.CharField(max_length=35, verbose_name="Limitation (cs)"),
                ),
                (
                    "limitation_en",
                    models.CharField(
                        blank=True,
                        max_length=35,
                        null=True,
                        verbose_name="Limitation (en)",
                    ),
                ),
            ],
        ),
    ]
