# Generated by Django 6.0.7 on 2026-07-17 11:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0032_copy_limitations_to_temp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tempmesuregroup",
            name="id",
        ),
        migrations.AlterField(
            model_name="tempmesuregroup",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="UUID",
            ),
        ),
    ]
