# Generated by Django 6.0.7 on 2026-07-17 11:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0033_remove_tempmesuregroup_id_alter_tempmesuregroup_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="templocationtype",
            name="id",
        ),
        migrations.AlterField(
            model_name="templocationtype",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="UUID",
            ),
        ),
    ]
