# Generated by Django 6.0.7 on 2026-07-17 11:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0035_remove_templimitation_id_alter_templimitation_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="TempAdvatageCategory",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "old_pk",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="Old primary key"
                    ),
                ),
                (
                    "advantage_category_cs",
                    models.CharField(
                        max_length=35, verbose_name="Advantage category (cs)"
                    ),
                ),
                (
                    "advantage_category_en",
                    models.CharField(
                        blank=True,
                        max_length=35,
                        null=True,
                        verbose_name="Advantage category (en)",
                    ),
                ),
            ],
        ),
    ]
