# Generated by Django 6.0.7 on 2026-07-17 11:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0037_copy_advatage_categories_to_temp"),
    ]

    operations = [
        migrations.CreateModel(
            name="TempAdvantage",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "old_pk",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="Old primary key"
                    ),
                ),
                (
                    "advantage_cs",
                    models.CharField(max_length=35, verbose_name="Advantage (cs)"),
                ),
                (
                    "advantage_en",
                    models.CharField(
                        blank=True,
                        max_length=35,
                        null=True,
                        verbose_name="Advantage (en)",
                    ),
                ),
            ],
        ),
    ]
