# Generated by Django 6.0.7 on 2026-07-17 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0038_tempadvantage"),
    ]

    operations = [
        migrations.AddField(
            model_name="tempadvantage",
            name="advantage_category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogue.tempadvatagecategory",
                verbose_name="Advantage category",
            ),
            preserve_default=False,
        ),
    ]
