# Generated by Django 6.0.7 on 2026-07-17 12:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0040_copy_advantages_to_temp"),
    ]

    operations = [
        migrations.CreateModel(
            name="TempPreDesign",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "old_pk",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="Old primary key"
                    ),
                ),
                (
                    "prereqisite",
                    models.CharField(max_length=255, verbose_name="Prerequisite"),
                ),
            ],
        ),
    ]
