# Generated by Django 6.0.7 on 2026-07-17 12:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0042_copy_predesigns_to_temp"),
    ]

    operations = [
        migrations.CreateModel(
            name="TempSDG",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "old_pk",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="Old primary key"
                    ),
                ),
                ("sdg_number", models.PositiveSmallIntegerField()),
                ("sdg_name", models.CharField(max_length=100)),
                (
                    "icon",
                    models.ImageField(blank=True, null=True, upload_to="sdg_icons"),
                ),
            ],
        ),
    ]
