# Generated by Django 6.0.7 on 2026-07-17 12:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0044_copy_sdgs_to_temp"),
    ]

    operations = [
        migrations.CreateModel(
            name="TempLaw",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "old_pk",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="Old primary key"
                    ),
                ),
                ("description", models.CharField(max_length=100)),
                ("url", models.URLField()),
            ],
        ),
    ]
