# Generated by Django 6.0.7 on 2026-07-17 12:26

import catalogue.fields
import django.db.models.deletion
import markdownx.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0046_copy_laws_to_temp"),
    ]

    operations = [
        migrations.CreateModel(
            name="TempMeasure",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "old_pk",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="Old primary key"
                    ),
                ),
                (
                    "name_cs",
                    models.CharField(max_length=100, verbose_name="Measure name (cs)"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Measure name (en)",
                    ),
                ),
                (
                    "short_description_cs",
                    models.CharField(
                        max_length=255, verbose_name="Measure short description (cs)"
                    ),
                ),
                (
                    "short_description_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Measure short description (en)",
                    ),
                ),
                (
                    "description_cs",
                    markdownx.models.MarkdownxField(
                        verbose_name="Measure description (cs)"
                    ),
                ),
                (
                    "description_en",
                    markdownx.models.MarkdownxField(
                        blank=True, null=True, verbose_name="Measure description (en)"
                    ),
                ),
                ("purpose", models.CharField(max_length=255)),
                (
                    "temperature",
                    catalogue.fields.ScoreField(verbose_name="Temperature"),
                ),
                ("water", catalogue.fields.ScoreField(verbose_name="Water")),
                (
                    "biodiversity",
                    catalogue.fields.ScoreField(verbose_name="Biodiversity"),
                ),
                ("air", catalogue.fields.ScoreField(verbose_name="Air")),
                ("aesthetics", catalogue.fields.ScoreField(verbose_name="Aesthetics")),
                (
                    "complexity_of_realization",
                    models.CharField(
                        choices=[("L", "Low"), ("M", "Medium"), ("H", "High")],
                        max_length=1,
                        verbose_name="Complexity of realization",
                    ),
                ),
                (
                    "budget_choices",
                    models.CharField(
                        choices=[("L", "Low"), ("M", "Medium"), ("H", "High")],
                        max_length=1,
                        verbose_name="Budget",
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Price"
                    ),
                ),
                ("units", models.CharField(max_length=10, verbose_name="Units")),
                (
                    "time_horizon",
                    models.CharField(
                        choices=[("L", "Low"), ("M", "Medium"), ("H", "High")],
                        max_length=1,
                        verbose_name="Time horizon",
                    ),
                ),
                (
                    "measure_size",
                    models.CharField(
                        choices=[("P", "Point"), ("L", "Line"), ("A", "Area")],
                        max_length=1,
                        verbose_name="Measure size",
                    ),
                ),
                ("diy", models.BooleanField(default=False, verbose_name="DIY")),
                (
                    "advantage",
                    models.ManyToManyField(
                        related_name="advantage",
                        to="catalogue.tempadvantage",
                        verbose_name="Advantage",
                    ),
                ),
                (
                    "combine",
                    models.ManyToManyField(
                        blank=True,
                        related_name="related_measures",
                        to="catalogue.tempmeasure",
                        verbose_name="Related measures",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogue.tempmesuregroup",
                        verbose_name="Measure group",
                    ),
                ),
                ("law", models.ManyToManyField(to="catalogue.templaw")),
                (
                    "limitation",
                    models.ManyToManyField(
                        to="catalogue.templimitation", verbose_name="Limitation"
                    ),
                ),
                (
                    "location_type",
                    models.ManyToManyField(
                        to="catalogue.templocationtype", verbose_name="Location type"
                    ),
                ),
                (
                    "main_advantage",
                    models.ManyToManyField(
                        related_name="main_advantage",
                        to="catalogue.tempadvantage",
                        verbose_name="Main advantage",
                    ),
                ),
                ("sdg", models.ManyToManyField(to="catalogue.tempsdg")),
            ],
        ),
    ]
