# Generated by Django 6.0.7 on 2026-07-17 12:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0048_copy_measures_to_temp"),
    ]

    operations = [
        migrations.CreateModel(
            name="TempPerformance",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "old_pk",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="Old primary key"
                    ),
                ),
                (
                    "performance",
                    models.CharField(max_length=100, verbose_name="Performance"),
                ),
                (
                    "measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogue.tempmeasure",
                    ),
                ),
            ],
        ),
    ]
