# Generated by Django 6.0.7 on 2026-07-17 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0050_copy_performances_to_temp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advantage",
            name="advantage_category",
        ),
        migrations.RemoveField(
            model_name="measure",
            name="advantage",
        ),
        migrations.RemoveField(
            model_name="measure",
            name="main_advantage",
        ),
        migrations.RemoveField(
            model_name="measure",
            name="law",
        ),
        migrations.RemoveField(
            model_name="measure",
            name="limitation",
        ),
        migrations.RemoveField(
            model_name="measure",
            name="location_type",
        ),
        migrations.RemoveField(
            model_name="measure",
            name="combine",
        ),
        migrations.RemoveField(
            model_name="measure",
            name="group",
        ),
        migrations.RemoveField(
            model_name="measure",
            name="sdg",
        ),
        migrations.RemoveField(
            model_name="performance",
            name="measure",
        ),
        migrations.DeleteModel(
            name="PreDesign",
        ),
        migrations.AlterModelOptions(
            name="tempadvantage",
            options={"verbose_name": "Advantage", "verbose_name_plural": "Advantages"},
        ),
        migrations.AlterModelOptions(
            name="tempadvatagecategory",
            options={
                "verbose_name": "Advantage category",
                "verbose_name_plural": "Advantage categories",
            },
        ),
        migrations.AlterModelOptions(
            name="templaw",
            options={
                "verbose_name": "Legislation",
                "verbose_name_plural": "Legislations",
            },
        ),
        migrations.AlterModelOptions(
            name="templimitation",
            options={
                "verbose_name": "Limitation",
                "verbose_name_plural": "Limitations",
            },
        ),
        migrations.AlterModelOptions(
            name="templocationtype",
            options={
                "verbose_name": "Location type",
                "verbose_name_plural": "Location types",
            },
        ),
        migrations.AlterModelOptions(
            name="tempmeasure",
            options={"verbose_name": "Measure", "verbose_name_plural": "Measures"},
        ),
        migrations.AlterModelOptions(
            name="tempmesuregroup",
            options={
                "verbose_name": "Measure group",
                "verbose_name_plural": "Measure groups",
            },
        ),
        migrations.AlterModelOptions(
            name="tempsdg",
            options={
                "verbose_name": "Sustainable Development Goal",
                "verbose_name_plural": "Sustainable Development Goals",
            },
        ),
        migrations.DeleteModel(
            name="AdvatageCategory",
        ),
        migrations.DeleteModel(
            name="Advantage",
        ),
        migrations.DeleteModel(
            name="Law",
        ),
        migrations.DeleteModel(
            name="Limitation",
        ),
        migrations.DeleteModel(
            name="LocationType",
        ),
        migrations.DeleteModel(
            name="MeasureGroup",
        ),
        migrations.DeleteModel(
            name="SDG",
        ),
        migrations.DeleteModel(
            name="Measure",
        ),
        migrations.DeleteModel(
            name="Performance",
        ),
    ]
