# Generated by Django 6.0.7 on 2026-07-17 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0051_remove_advantage_advantage_category_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TempAdvantage",
            new_name="Advantage",
        ),
        migrations.RenameModel(
            old_name="TempAdvatageCategory",
            new_name="AdvatageCategory",
        ),
        migrations.RenameModel(
            old_name="TempLaw",
            new_name="Law",
        ),
        migrations.RenameModel(
            old_name="TempLimitation",
            new_name="Limitation",
        ),
        migrations.RenameModel(
            old_name="TempLocationType",
            new_name="LocationType",
        ),
        migrations.RenameModel(
            old_name="TempMeasure",
            new_name="Measure",
        ),
        migrations.RenameModel(
            old_name="TempMesureGroup",
            new_name="MeasureGroup",
        ),
        migrations.RenameModel(
            old_name="TempPerformance",
            new_name="Performance",
        ),
        migrations.RenameModel(
            old_name="TempPreDesign",
            new_name="PreDesign",
        ),
        migrations.RenameModel(
            old_name="TempSDG",
            new_name="SDG",
        ),
    ]
