# Generated by Django 6.0.7 on 2026-07-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0052_rename_tempadvantage_advantage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measuregroup",
            name="icon",
            field=models.ImageField(
                upload_to="measure_groups", verbose_name="Measure group icon"
            ),
        ),
    ]
