# Generated by Django 6.0.7 on 2026-07-17 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0053_alter_measuregroup_icon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advantage",
            name="old_pk",
        ),
        migrations.RemoveField(
            model_name="advatagecategory",
            name="old_pk",
        ),
        migrations.RemoveField(
            model_name="law",
            name="old_pk",
        ),
        migrations.RemoveField(
            model_name="limitation",
            name="old_pk",
        ),
        migrations.RemoveField(
            model_name="locationtype",
            name="old_pk",
        ),
        migrations.RemoveField(
            model_name="measure",
            name="old_pk",
        ),
        migrations.RemoveField(
            model_name="measuregroup",
            name="old_pk",
        ),
        migrations.RemoveField(
            model_name="performance",
            name="old_pk",
        ),
        migrations.RemoveField(
            model_name="predesign",
            name="old_pk",
        ),
        migrations.RemoveField(
            model_name="sdg",
            name="old_pk",
        ),
    ]
