# Generated by Django 6.0.7 on 2026-07-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0054_remove_advantage_old_pk_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="measure",
            name="groups",
            field=models.ManyToManyField(
                related_name="measures",
                to="catalogue.measuregroup",
                verbose_name="Measure groups",
            ),
        ),
    ]
