# Generated by Django 6.0.7 on 2026-07-20 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0056_copy_measure_group_to_groups"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="measure",
            name="group",
        ),
    ]
