# Generated by Django 6.0.7 on 2026-07-20 09:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0057_remove_measure_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="measure",
            name="municipality_size",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("S", "< 2,000 inhabitants"),
                        ("M", "2,000 – 10,000 inhabitants"),
                        ("L", "10,000 – 50,000 inhabitants"),
                        ("XL", "> 50,000 inhabitants"),
                    ],
                    max_length=2,
                ),
                blank=True,
                default=list,
                verbose_name="Municipality size",
            ),
        ),
    ]
