# Generated by Django 6.0.7 on 2026-07-20 09:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0059_alter_measure_municipality_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="MainProblems",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "problem_cs",
                    models.CharField(max_length=100, verbose_name="Problem (cs)"),
                ),
                (
                    "problem_en",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Problem (en)",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(blank=True, null=True, upload_to="main_problems"),
                ),
            ],
            options={
                "verbose_name": "Main problem",
                "verbose_name_plural": "Main problems",
            },
        ),
    ]
