# Generated by Django 6.0.7 on 2026-07-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0060_mainproblems"),
    ]

    operations = [
        migrations.AddField(
            model_name="measure",
            name="main_problems",
            field=models.ManyToManyField(
                related_name="main_problems",
                to="catalogue.mainproblems",
                verbose_name="Main problems",
            ),
        ),
    ]
