# Generated by Django 6.0.7 on 2026-07-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0061_measure_main_problems"),
    ]

    operations = [
        migrations.AddField(
            model_name="measure",
            name="when_and_why_to_use_cs",
            field=models.TextField(default=1, verbose_name="When and why to use (cs)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="measure",
            name="when_and_why_to_use_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="When and why to use (en)"
            ),
        ),
    ]
