# Generated by Django 6.0.7 on 2026-07-20 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0062_measure_when_and_why_to_use_cs_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeasureCombination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description_cs",
                    models.TextField(
                        blank=True, verbose_name="Combination description (cs)"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Combination description (en)",
                    ),
                ),
                (
                    "from_measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="combination_from",
                        to="catalogue.measure",
                        verbose_name="Measure",
                    ),
                ),
                (
                    "to_measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="combination_to",
                        to="catalogue.measure",
                        verbose_name="Related measure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Measure combination",
                "verbose_name_plural": "Measure combinations",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("from_measure", "to_measure"),
                        name="unique_measure_combination",
                    )
                ],
            },
        ),
    ]
