# Generated by Django 6.0.7 on 2026-07-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0063_measurecombination"),
    ]

    operations = [
        migrations.AddField(
            model_name="measure",
            name="new_combine",
            field=models.ManyToManyField(
                blank=True,
                related_name="related_measures",
                through="catalogue.MeasureCombination",
                through_fields=("from_measure", "to_measure"),
                to="catalogue.measure",
                verbose_name="Related measures",
            ),
        ),
        migrations.AlterField(
            model_name="measure",
            name="combine",
            field=models.ManyToManyField(
                blank=True,
                related_name="r_measures",
                to="catalogue.measure",
                verbose_name="Related measures",
            ),
        ),
    ]
