# Generated by Django 6.0.7 on 2026-07-20 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0065_copy_combine_to_measurecombination"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="measure",
            name="combine",
        ),
    ]
