# Generated by Django 6.0.7 on 2026-07-20 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0066_remove_measure_combine"),
    ]

    operations = [
        migrations.RenameField(
            model_name="measure",
            old_name="new_combine",
            new_name="combine",
        ),
    ]
