# Generated by Django 6.0.7 on 2026-07-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0067_rename_new_combine_measure_combine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurecombination",
            name="description_cs",
            field=models.CharField(
                blank=True, verbose_name="Combination description (cs)"
            ),
        ),
        migrations.AlterField(
            model_name="measurecombination",
            name="description_en",
            field=models.CharField(
                blank=True, null=True, verbose_name="Combination description (en)"
            ),
        ),
    ]
