# Generated by Django 6.0.7 on 2026-07-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0068_alter_measurecombination_description_cs_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurecombination",
            name="description_cs",
            field=models.CharField(verbose_name="Combination description (cs)"),
        ),
    ]
