# Generated by Django 6.0.7 on 2026-07-20 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0069_alter_measurecombination_description_cs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="measurecombination",
            name="description_cs",
        ),
        migrations.RemoveField(
            model_name="measurecombination",
            name="description_en",
        ),
    ]
