# Generated by Django 6.0.7 on 2026-07-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0070_remove_measurecombination_description_cs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurecombination",
            name="description",
            field=models.CharField(
                blank=True,
                choices=[
                    ("related", "related"),
                    ("compatible", "compatibile with"),
                    ("requires", "requires"),
                ],
                max_length=10,
                null=True,
                verbose_name="Description",
            ),
        ),
    ]
