# Generated by Django 6.0.7 on 2026-07-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0071_measurecombination_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurecombination",
            name="description",
            field=models.CharField(
                blank=True,
                choices=[
                    ("similar", "similar to"),
                    ("compatible", "compatibile with"),
                    ("requires", "requires"),
                ],
                max_length=10,
                null=True,
                verbose_name="Description",
            ),
        ),
    ]
