# Generated by Django 6.0.7 on 2026-07-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0072_alter_measurecombination_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="law",
            old_name="description",
            new_name="description_cs",
        ),
        migrations.AddField(
            model_name="law",
            name="description_en",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
