# Generated by Django 6.0.7 on 2026-07-20 11:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0073_rename_description_law_description_cs_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FundingOpportunity",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "description_cs",
                    models.CharField(max_length=100, verbose_name="Description (cs)"),
                ),
                (
                    "description_en",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Description (en)",
                    ),
                ),
                ("url", models.URLField()),
            ],
            options={
                "verbose_name": "Founding opportunity",
                "verbose_name_plural": "Founding opportunities",
            },
        ),
        migrations.AlterField(
            model_name="law",
            name="description_cs",
            field=models.CharField(max_length=100, verbose_name="Description (cs)"),
        ),
        migrations.AlterField(
            model_name="law",
            name="description_en",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Description (en)"
            ),
        ),
    ]
