# Generated by Django 6.0.7 on 2026-07-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0074_fundingopportunity_alter_law_description_cs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="measure",
            name="funding_opportunity",
            field=models.ManyToManyField(
                related_name="funding_opportunity",
                to="catalogue.fundingopportunity",
                verbose_name="Funding opportunity",
            ),
        ),
    ]
