# Generated by Django 6.0.7 on 2026-07-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0075_measure_funding_opportunity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measure",
            name="funding_opportunity",
            field=models.ManyToManyField(
                blank=True,
                related_name="funding_opportunity",
                to="catalogue.fundingopportunity",
                verbose_name="Funding opportunity",
            ),
        ),
    ]
