# Generated by Django 6.0.7 on 2026-07-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0076_alter_measure_funding_opportunity"),
    ]

    operations = [
        migrations.AddField(
            model_name="measuregroup",
            name="slug_cs",
            field=models.SlugField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Measure group slug (cs)",
            ),
        ),
        migrations.AddField(
            model_name="measuregroup",
            name="slug_en",
            field=models.SlugField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Measure group slug (en)",
            ),
        ),
    ]
