# Generated by Django 6.0.7 on 2026-07-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0079_measuregroup_created_at_measuregroup_last_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="measuregroup",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is active"),
        ),
        migrations.AddField(
            model_name="measuregroup",
            name="ordering",
            field=models.IntegerField(default=0, verbose_name="Ordering"),
        ),
        migrations.AddField(
            model_name="measuregroup",
            name="short_description_cs",
            field=models.CharField(
                default=1,
                max_length=255,
                verbose_name="Measure group short description (cs)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="measuregroup",
            name="short_description_en",
            field=models.CharField(
                blank=True,
                null=True,
                verbose_name="Measure group short description (en)",
            ),
        ),
    ]
