# Generated by Django 6.0.7 on 2026-07-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0080_measuregroup_is_active_measuregroup_ordering_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="measuregroup",
            name="short_description_cs",
        ),
        migrations.RemoveField(
            model_name="measuregroup",
            name="short_description_en",
        ),
        migrations.AddField(
            model_name="measuregroup",
            name="short_name_cs",
            field=models.CharField(
                default=1, max_length=255, verbose_name="Measure group short name (cs)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="measuregroup",
            name="short_name_en",
            field=models.CharField(
                blank=True, null=True, verbose_name="Measure group short name (en)"
            ),
        ),
    ]
