# Generated by Django 6.0.7 on 2026-07-22 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0081_remove_measuregroup_short_description_cs_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="measuregroup",
            options={
                "ordering": ["ordering"],
                "verbose_name": "Measure group",
                "verbose_name_plural": "Measure groups",
            },
        ),
    ]
