# Generated by Django 6.0.7 on 2026-07-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0082_alter_measuregroup_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="measure",
            name="slug_cs",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="measure",
            name="slug_en",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
