# Generated by Django 6.0.7 on 2026-07-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0084_populate_measure_slugs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measure",
            name="slug_cs",
            field=models.SlugField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
