# Generated by Django 6.0.7 on 2026-07-26 10:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0085_alter_measure_slug_cs"),
    ]

    operations = [
        migrations.AddField(
            model_name="measure",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="measure",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
