# Generated by Django 6.0.7 on 2026-08-04 11:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0089_advatagecategory_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="advantage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="advantage",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
