# Generated by Django 6.0.7 on 2026-08-04 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0090_advantage_created_at_advantage_last_modified"),
    ]

    operations = [
        migrations.RenameField(
            model_name="predesign",
            old_name="prereqisite",
            new_name="prereqisite_cs",
        ),
    ]
