# Generated by Django 6.0.7 on 2026-08-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0091_rename_prereqisite_predesign_prereqisite_cs"),
    ]

    operations = [
        migrations.AddField(
            model_name="predesign",
            name="prereqisite_en",
            field=models.CharField(
                default=1, max_length=255, verbose_name="Prerequisite (English)"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="predesign",
            name="prereqisite_cs",
            field=models.CharField(max_length=255, verbose_name="Prerequisite (Czech)"),
        ),
    ]
