# Generated by Django 6.0.7 on 2026-08-04 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0093_predesign_created_at_predesign_last_modified"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="predesign",
            options={
                "verbose_name": "Prerequisite",
                "verbose_name_plural": "Prerequisites",
            },
        ),
    ]
