# Generated by Django 6.0.7 on 2026-08-04 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0094_alter_predesign_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PreDesign",
            new_name="Prerequisite",
        ),
    ]
