# Generated by Django 6.0.7 on 2026-09-02 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0095_rename_predesign_prerequisite"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sdg",
            old_name="sdg_name",
            new_name="sdg_name_cs",
        ),
    ]
