# Generated by Django 6.0.7 on 2026-09-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0096_rename_sdg_name_sdg_sdg_name_cs"),
    ]

    operations = [
        migrations.AddField(
            model_name="sdg",
            name="sdg_name_en",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
